import { collection, getDocs, query, where } from 'firebase/firestore';
import { db } from '../services/firebase';
import { generateInvoice } from '../services/invoiceService';

/**
 * Generate invoices for ALL families with payments (no agency filter)
 * Use this when families don't have agencyId field
 * @param {string} targetAgencyId - Agency ID to assign to generated invoices
 */
export const generateInvoicesForAllFamilies = async (targetAgencyId) => {
    try {
        console.log('🔄 Starting invoice generation for ALL families...');
        console.log('='.repeat(60));

        // Get ALL families
        const familiesRef = collection(db, 'families');
        const familiesSnapshot = await getDocs(familiesRef);

        console.log(`📋 Found ${familiesSnapshot.size} total families\n`);

        let totalInvoicesGenerated = 0;
        let totalPaymentsProcessed = 0;
        let familiesWithPayments = 0;
        const errors = [];

        // Process each family
        for (const familyDoc of familiesSnapshot.docs) {
            const bookingId = familyDoc.id;
            const familyData = familyDoc.data();

            console.log(`\n👥 Processing: ${familyData.displayName || familyData.bookingCode || bookingId}`);

            try {
                // Get all payments for this family
                const paymentsRef = collection(db, 'families', bookingId, 'payments');
                const paymentsSnapshot = await getDocs(paymentsRef);

                if (paymentsSnapshot.empty) {
                    console.log('   ⏭️ No payments found, skipping...');
                    continue;
                }

                familiesWithPayments++;
                console.log(`   💰 Found ${paymentsSnapshot.size} payments`);

                // Process each payment directly without checking for existing invoices
                // (to avoid permission issues with querying invoices collection)
                for (const paymentDoc of paymentsSnapshot.docs) {
                    const paymentId = paymentDoc.id;

                    try {
                        // Generate invoice for this payment
                        console.log(`   ✨ Generating invoice for payment ${paymentId}...`);
                        await generateInvoice(bookingId, [paymentId], {
                            autoGenerated: false,
                            agencyId: targetAgencyId // Force agency ID
                        });
                        totalInvoicesGenerated++;
                        totalPaymentsProcessed++;
                        console.log(`   ✅ Invoice generated!`);
                    } catch (paymentError) {
                        // If error is "already exists" or similar, that's OK
                        if (paymentError.message && paymentError.message.includes('already')) {
                            console.log(`   ⏭️ Payment ${paymentId} already has invoice`);
                        } else {
                            console.error(`   ❌ Error:`, paymentError.message);
                            errors.push({
                                bookingId,
                                bookingCode: familyData.bookingCode || bookingId,
                                paymentId,
                                error: paymentError.message
                            });
                        }
                    }
                }
            } catch (familyError) {
                console.error(`❌ Error processing family ${bookingId}:`, familyError);
                errors.push({
                    bookingId,
                    bookingCode: familyData.bookingCode || bookingId,
                    error: familyError.message
                });
            }
        }

        // Summary
        console.log('\n' + '='.repeat(60));
        console.log('📊 INVOICE GENERATION SUMMARY');
        console.log('='.repeat(60));
        console.log(`✅ Invoices generated: ${totalInvoicesGenerated}`);
        console.log(`💰 Payments processed: ${totalPaymentsProcessed}`);
        console.log(`👥 Total families: ${familiesSnapshot.size}`);
        console.log(`💵 Families with payments: ${familiesWithPayments}`);

        if (errors.length > 0) {
            console.log(`\n⚠️ Errors: ${errors.length}`);
            errors.forEach((err, index) => {
                console.log(`\n${index + 1}. Family: ${err.bookingCode}`);
                console.log(`   Payment: ${err.paymentId || 'N/A'}`);
                console.log(`   Error: ${err.error}`);
            });
        }

        console.log('\n' + '='.repeat(60));

        return {
            success: true,
            totalInvoicesGenerated,
            totalPaymentsProcessed,
            totalFamilies: familiesSnapshot.size,
            familiesWithPayments,
            errors
        };
    } catch (error) {
        console.error('❌ Fatal error:', error);
        throw error;
    }
};
